'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../blog/posts/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

//  wrapper.init(liveFunction); // Run the deployed lambda
wrapper.init(mod, {
  handler: 'create'
});

describe('API create', () => {
  it('creates a post', (done) => {
    wrapper.run({
        "method": "POST",
        "stage": "dev",
        "body": {
          "title": "Test post",
          "content" : "Test content"
        }
    }, (err, response) => {
      done();
      return;
      console.trace(response);
      expect(err).to.be.null;
      expect(response.post.id).to.be.not.null;
      done();
    });
  });
});
