'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../blog/posts/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const lambdaWrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

//  wrapper.init(liveFunction); // Run the deployed lambda
const getPostsWrapped = lambdaWrapper.wrap(mod, { handler: 'getPosts' });

describe('API get', () => {
  let postId;

  it('reads posts', (done) => {
    getPostsWrapped.run({
        "method": "GET",
        "stage": "dev",
    }, (err, response) => {
      expect(err).to.be.null;
      expect(response.Items).to.be.defined;
      expect(response.Count).to.be.defined;
      done();
    });
  });
});
