'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../blog/posts/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

//  wrapper.init(liveFunction); // Run the deployed lambda
wrapper.init(mod, {
  handler: 'getPosts'
});

describe('API get', () => {
  let postId;

  it('reads posts', (done) => {
    wrapper.run({
        "method": "GET",
        "stage": "dev",
    }, (err, response) => {
      expect(err).to.be.null;        
      expect('to be implemented').to.be.null;
      done();
    });
  });
});
