'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

describe('hello', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda 
    wrapper.init(mod, {
      handler: 'hello'
    });

    done()
  })
  
  it('test GET', (done) => {
    wrapper.run({
      "method": "GET"
    }, (err, response) => {
      expect(response.message).to.be.equal("Go Serverless v1.0! Your function executed successfully!")
      done()
    });
  });
});