'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../blog/posts/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

wrapper.init(mod);

describe('posts', () => {
  let postId;
  it('creates a post', (done) => {
    wrapper.run({ 
        "method": "POST", 
        "body": { 
          "title": "Test post", 
          "content" : "Test content" 
        }
    }, (err, response) => {
      postId = response.post.id;
      expect(response.post.id).to.be.not.null;
      expect(err).to.be.null;
      done();
    });
  });
  
  it('deletes a post', (done) => {
    wrapper.run({ 
        "method": "DELETE", 
        "id": postId
    }, (err, response) => {
      expect(err).to.be.null;
      done();
    });
  });
});
