'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod                = require('../blog/posts/handler.js');
const mochaPlugin        = require('serverless-mocha-plugin');
const lambdaWrapper      = mochaPlugin.lambdaWrapper;
const expect             = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

//  wrapper.init(liveFunction); // Run the deployed lambda
const removePostWrapped = lambdaWrapper.wrap(mod, { handler: 'removePost' });

describe('API remove', () => {

  it('deletes a post', (done) => {
    removePostWrapped.run({
        "method": "DELETE",
        "stage": "dev",
        "path": {
          "id": '1472459044212',
        },
    }, (err, response) => {
      expect(err).to.be.null;
      done();
    });
  });
});
