'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod         = require('../blog/posts/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-handler'
}

//  wrapper.init(liveFunction); // Run the deployed lambda
wrapper.init(mod, {
  handler: 'remove'
});

describe('API remove', () => {
  let postId;

  it('deletes a post', (done) => {
    wrapper.run({
        "method": "DELETE",
        "stage": "dev",
        "path": {
          "id": postId,
        },
    }, (err, response) => {
      expect('to be implemented').to.be.null;
      done();
    });
  });
});
