'use strict';
// tests for posts
// Generated by serverless-mocha-plugin

const mod               = require('../blog/posts/handler.js');
const mochaPlugin       = require('serverless-mocha-plugin');

const lambdaWrapper     = mochaPlugin.lambdaWrapper;
const expect            = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: `${process.env.SERVERLESS_PROJECT}-handler`,
};

//  wrapper.init(liveFunction); // Run the deployed lambda
const updatePostWrapped = lambdaWrapper.wrap(mod, { handler: 'updatePost' })

describe('API update', () => {

  it('updates or adds a post if it doesn\'t exist yet', (done) => {
    updatePostWrapped.run({
        'method': 'PUT',
        'stage': 'dev',
        'path': {
          'id': '1472459044212',
        },
        'body': {
          'title': 'Test post updated',
          'content' : 'Test content updated'
        }
    }, (err, response) => {
      expect(err).to.be.null;
      expect(response.post.id).to.equal('1472459044212');
      expect(response.post.title).to.equal('Test post updated');
      expect(response.post.content).to.equal('Test content updated');
      done();
    });
  });
});
